FROM postgres:${PG_VERSION}-alpine

ENV PYTHON=python3
RUN apk add --no-cache build-base curl python3 py-virtualenv python3-dev musl
ENV LANG=C.UTF-8

RUN mkdir -p /pg
COPY run_tests.sh /run.sh
RUN chmod 755 /run.sh

ADD . /pg/testgres
WORKDIR /pg/testgres
RUN chown -R postgres:postgres /pg

USER postgres
ENTRYPOINT PYTHON=${PYTHON} /run.sh
