FROM postgres:${PG_VERSION}-alpine

ENV PYTHON=python${PYTHON_VERSION}
RUN if [ "${PYTHON_VERSION}" = "2" ] ; then \
	apk add --no-cache python py-pip; \
	pip install six pg8000 flake8 port-for; \
	fi
RUN if [ "${PYTHON_VERSION}" = "3" ] ; then \
	apk add --no-cache python3; \
	pip3 install six pg8000 flake8 port-for; \
	fi
ENV LANG=C.UTF-8

RUN mkdir -p /pg
VOLUME /pg
COPY run_tests.sh /run.sh
RUN chmod 755 /run.sh

ADD . /pg/testgres
WORKDIR /pg/testgres
RUN	${PYTHON} setup.py install

USER postgres
ENTRYPOINT PYTHON=${PYTHON} /run.sh
