ARG PG_VERSION
ARG PYTHON_VERSION 

# --------------------------------------------- base1
FROM postgres:${PG_VERSION}-alpine as base1

# --------------------------------------------- base2_with_python-3
FROM base1 as base2_with_python-3
RUN apk add --no-cache curl python3 python3-dev build-base musl-dev linux-headers
ENV PYTHON_BINARY=python3

# --------------------------------------------- final
FROM base2_with_python-${PYTHON_VERSION} as final

RUN apk add --no-cache git

ENV LANG=C.UTF-8

ADD --chown=postgres:postgres . /pg/testgres
WORKDIR /pg/testgres

USER postgres
ENTRYPOINT bash run_tests.sh
